//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolidWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        public int Id { get; set; }
        public int IdPropietario { get; set; }
        public string Tipo { get; set; }
        public string Nro { get; set; }
        public string Piso { get; set; }
        public decimal Area { get; set; }
        public decimal Porcentaje { get; set; }
        public bool Habitado { get; set; }
        public bool Descuento { get; set; }
        public decimal MontoDescuento { get; set; }
    
        public virtual Propietario Propietario { get; set; }
    }
}
